### ISSUE TITLE
defer_retry_wake passes schedule_in as task kwarg instead of procrastinate directive (breaks exponential backoff from #71)

### ISSUE THREAD

**Issue by eumemic** [eumemic/aios#80]
## Observed

After tonight's gpt-oss-20b context-overflow 400, the exponential-backoff retry path introduced in #71 fires but fails with:

```
TypeError: wake_session() got an unexpected keyword argument 'schedule_in'
Job harness.wake_session[4512](cause='reschedule', session_id='sess_01KPCX...',
    schedule_in={'seconds': 2}) ended with status: Error, lasted 0.001 s
```

Every retry attempt (``[2, 8, 30, 120]`` delays) raises the same error, so no retry actually lands.  The session stays stuck until the periodic sweep eventually re-wakes it — which is exactly the ~30s floor #71 was supposed to fix.

## Root cause

In ``src/aios/harness/wake.py::defer_retry_wake``:

```python
await app.configure_task("harness.wake_session").defer_async(
    session_id=session_id,
    cause="reschedule",
    schedule_in={"seconds": delay_seconds},  # ← treated as a task kwarg
)
```

``procrastinate.Task.defer_async(**kwargs)`` forwards ``kwargs`` to the task function.  So ``schedule_in={'seconds': ...}`` is being passed as an argument to ``wake_session(session_id, cause, ...)``, which doesn't accept it — hence the ``TypeError``.

Procrastinate's delayed-scheduling API uses a different method on the configured task (something like ``.configure(schedule_in=timedelta(...))`` or a ``schedule_at`` parameter on a different chained call).  The correct invocation wasn't used.

## Impact

- #71 is effectively inert: every retry attempt errors out at defer time, so the retry never runs.
- Recovery falls back to the periodic sweep — the exact ~30s floor #71 was meant to eliminate.
- The ``schedule_in`` TypeError is a visible red flag in the worker log but the session still recovers, so it's easy to miss.

## What a fix looks like (not prescribing)

- Use the correct procrastinate method to schedule a delayed ``defer_async``.  Procrastinate's docs/source have the canonical call shape; ``schedule_in`` belongs on a scheduling directive, not in the task's ``**kwargs``.
- Regression test: a unit or e2e test that calls ``defer_retry_wake`` and asserts the job lands in procrastinate's queue with a scheduled-for timestamp in the future (not that it errors out).

## Related

- #71 / #54 — the PR / issue this regressed from.  The backoff values (``[2, 8, 30, 120]``) and call-site in ``run_session_step`` are correct; only the procrastinate call inside ``defer_retry_wake`` is broken.

## Priority

Medium.  Not user-visible under the current behavior (session still recovers via sweep), but the whole point of #71 was faster recovery on transient errors — and that's currently dead code.
